version: '3.8'

services:
  pdf-service:
    build: .
    container_name: huawei-pdf-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PDF_SERVICE_KEY=huawei-pdf-2024-secure-key
      - PORT=3000
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    networks:
      - pdf-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.5'

  nginx:
    image: nginx:alpine
    container_name: huawei-pdf-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - pdf-service
    networks:
      - pdf-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 可选：Redis缓存（如需要缓存PDF）
  redis:
    image: redis:alpine
    container_name: huawei-pdf-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass huawei-redis-2024
    volumes:
      - redis-data:/data
    networks:
      - pdf-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 可选：监控服务
  watchtower:
    image: containrrr/watchtower
    container_name: huawei-pdf-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 2 * * *  # 每天凌晨2点检查更新
    networks:
      - pdf-network

networks:
  pdf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-data:
    driver: local
