#!/bin/bash

# 在代理服务器上创建验证脚本的命令
echo "=== 创建CAS代理服务器验证脚本 ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 登录到代理服务器："
echo "   ssh bupt@10.3.58.3"
echo ""
echo "2. 创建验证脚本："
echo ""
echo "cat > ~/verify-proxy.sh << 'EOF'"
echo "#!/bin/bash"
echo "echo \"=== CAS代理服务器验证脚本 ===\""
echo "echo \"\""
echo ""
echo "# 1. 健康检查"
echo "echo \"1. 检查代理服务器健康状态...\""
echo "if curl -f -s http://10.3.58.3:8080/health > /dev/null; then"
echo "    echo \"✅ 代理服务器健康检查通过\""
echo "    curl -s http://10.3.58.3:8080/health | jq . 2>/dev/null || curl -s http://10.3.58.3:8080/health"
echo "else"
echo "    echo \"❌ 代理服务器健康检查失败\""
echo "fi"
echo "echo \"\""
echo ""
echo "# 2. CAS回调测试"
echo "echo \"2. 测试CAS回调转发...\""
echo "REDIRECT_URL=\$(curl -s -I \"http://10.3.58.3:8080/api/auth/cas/callback?ticket=test\" | grep -i location | cut -d' ' -f2 | tr -d '\\r')"
echo "if [[ \"\$REDIRECT_URL\" == *\"butp.tech\"* ]]; then"
echo "    echo \"✅ CAS回调转发正常\""
echo "    echo \"   重定向到: \$REDIRECT_URL\""
echo "else"
echo "    echo \"❌ CAS回调转发异常: \$REDIRECT_URL\""
echo "fi"
echo "echo \"\""
echo ""
echo "# 3. SSL证书检查"
echo "echo \"3. 检查SSL证书...\""
echo "if openssl s_client -connect butp.tech:443 -servername butp.tech < /dev/null 2>/dev/null | grep -q \"Verify return code: 0\"; then"
echo "    echo \"✅ SSL证书验证通过\""
echo "    # 显示证书有效期"
echo "    CERT_DATES=\$(echo | openssl s_client -connect butp.tech:443 -servername butp.tech 2>/dev/null | openssl x509 -noout -dates)"
echo "    echo \"   \$CERT_DATES\""
echo "else"
echo "    echo \"❌ SSL证书验证失败\""
echo "fi"
echo "echo \"\""
echo ""
echo "# 4. 网络连通性"
echo "echo \"4. 测试网络连通性...\""
echo "if curl -f -s https://butp.tech/ > /dev/null; then"
echo "    echo \"✅ 网络连通性正常\""
echo "    # 测试延迟"
echo "    PING_TIME=\$(ping -c 1 butp.tech 2>/dev/null | grep \"time=\" | cut -d'=' -f4)"
echo "    if [ ! -z \"\$PING_TIME\" ]; then"
echo "        echo \"   网络延迟: \$PING_TIME\""
echo "    fi"
echo "else"
echo "    echo \"❌ 网络连通性异常\""
echo "fi"
echo "echo \"\""
echo ""
echo "# 5. PM2进程状态"
echo "echo \"5. 检查PM2进程状态...\""
echo "if pm2 list | grep -q \"cas-proxy.*online\"; then"
echo "    echo \"✅ PM2进程运行正常\""
echo "    pm2 list | grep cas-proxy"
echo "else"
echo "    echo \"❌ PM2进程状态异常\""
echo "    pm2 list"
echo "fi"
echo "echo \"\""
echo ""
echo "echo \"=== 验证完成 ===\""
echo "EOF"
echo ""
echo "3. 设置执行权限："
echo "   chmod +x ~/verify-proxy.sh"
echo ""
echo "4. 运行验证脚本："
echo "   ./verify-proxy.sh"
echo ""
echo "=== 创建完成 ===" 