"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

// 语言类型
export type Language = 'zh' | 'en'

// 语言上下文类型
interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

// 创建上下文
const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 翻译对象 - 目前只包含登录页面
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // 登录页面
    'login.title.line1': 'Build Your Toolbox',
    'login.title.line2': 'BuTP', 
    'login.description': '请输入您的学号哈希值登录',
    'login.select.label': '选择学生账号',
    'login.select.placeholder': '请选择学生...',
    'login.input.label': '请输入学号哈希值',
    'login.input.placeholder': '请输入64位哈希值',
    'login.alert.input': '请输入学号哈希值',
    'login.alert.invalid': '请输入有效的学号哈希值',
    'login.alert.failed': '登录失败，请重试',
    'login.button.login': '登录BuTP',
    'login.button.loading': '登录中...',
    'login.demo.text': '演示版本 • 仅供学习使用',
    'login.language.switch': 'Change to English',
    'login.alert.select': '请选择一个学生账号',
    
    // 侧边栏
    'sidebar.profile': '我的信息',
    'sidebar.logout': '退出登录',
    'sidebar.rolemodels': '职业分析',
    'sidebar.charts': '图表测试',
    'sidebar.analysis': '学业分析',
    
    // Profile页面
    'profile.title': '我的信息',
    'profile.description': '管理您的个人信息和设置',
    'profile.loading': '正在加载学生信息',
    'profile.awards.title': '获奖记录',
    'profile.awards.description': '您获得的奖项和荣誉',
    'profile.awards.add': '添加获奖',
    'profile.awards.empty': '当前栏暂无信息',
    'profile.awards.form.title': '添加获奖记录',
    'profile.awards.form.edit': '编辑获奖记录',
    'profile.awards.form.name': '奖项名称',
    'profile.awards.form.organization': '颁发单位/学年',
    'profile.awards.form.level': '级别',
    'profile.awards.form.level.placeholder': '请选择级别',
    'profile.awards.form.level.national': '国家级',
    'profile.awards.form.level.provincial': '省级',
    'profile.awards.form.level.municipal': '市级',
    'profile.awards.form.level.school': '校级',
    'profile.awards.form.level.other': '其他',
    'profile.awards.form.date': '获奖日期 (选填)',
    'profile.awards.form.date.placeholder': '例如：2024年6月',
    'profile.work.title': '工作经历',
    'profile.work.description': '您的实习和工作经历',
    'profile.work.add': '添加工作',
    'profile.work.empty': '当前栏暂无信息',
    'profile.work.form.title': '添加工作经历',
    'profile.work.form.edit': '编辑工作经历',
    'profile.work.form.position': '职位名称 *',
    'profile.work.form.position.placeholder': '例如：教学助理实习生',
    'profile.work.form.company': '公司/组织 *',
    'profile.work.form.company.placeholder': '例如：新东方教育科技集团',
    'profile.work.form.period': '工作时间 (选填)',
    'profile.work.form.period.placeholder': '例如：2024年7月 - 2024年8月',
    'profile.work.form.description': '工作描述 *',
    'profile.work.form.description.placeholder': '请简要描述您的工作内容和收获',
    'profile.language.title': '认证证书',
    'profile.language.description': '托福、雅思、GRE等标准化考试成绩',
    'profile.language.add': '添加成绩',
    'profile.language.empty': '当前栏暂无信息',
    'profile.language.toefl.reading': '阅读',
    'profile.language.toefl.listening': '听力',
    'profile.language.toefl.speaking': '口语',
    'profile.language.toefl.writing': '写作',
    'profile.language.ielts.listening': '听力',
    'profile.language.ielts.reading': '阅读',
    'profile.language.ielts.writing': '写作',
    'profile.language.ielts.speaking': '口语',
    'profile.language.gre.math': '数学',
    'profile.language.gre.verbal': '语文',
    'profile.language.gre.writing': '写作',
    'profile.language.form.title': '添加成绩',
    'profile.language.form.edit': '更新成绩',
    'profile.language.form.type': '考试类型',
    'profile.language.form.type.placeholder': '请选择考试类型',
    'profile.language.form.total': '总分',
    'profile.language.form.toefl.max': '最高30分',
    'profile.language.form.ielts.example': '例如: 7.5',
    'profile.language.form.gre.max': '最高170分',
    'profile.language.form.gre.writing.example': '例如: 4.5',
    'profile.common.cancel': '取消',
    'profile.common.save': '保存',
    'profile.common.delete': '删除',
    'profile.common.confirm.delete': '确认删除',
    'profile.common.confirm.delete.award': '您确定要删除这条获奖记录吗？',
    'profile.common.confirm.delete.work': '您确定要删除这条工作经历吗？',
    'profile.common.confirm.delete.toefl': '您确定要删除托福成绩吗？',
    'profile.common.confirm.delete.ielts': '您确定要删除雅思成绩吗？',
    'profile.common.confirm.delete.gre': '您确定要删除GRE成绩吗？',
    'profile.common.confirm.delete.note': '此操作无法撤销。',
    
    // 其他信息部分
    'profile.other.title': '其他信息',
    'profile.other.description': '记录您的MBTI、兴趣爱好、技能专长等个人特质信息',
    'profile.other.add': '添加信息',
    'profile.other.empty': '暂无其他信息，点击上方按钮添加',
    'profile.other.form.title': '添加其他信息',
    'profile.other.form.edit': '编辑其他信息',
    'profile.other.form.category': '类别',
    'profile.other.form.category.placeholder': '请选择类别',
    'profile.other.form.title.field': '标题',
    'profile.other.form.title.placeholder': '如：MBTI类型、编程技能等',
    'profile.other.form.content': '内容',
    'profile.other.form.content.placeholder': '如：INTJ | Python、Java、React | 阅读、旅行、摄影',
    'profile.common.confirm.delete.other': '您确定要删除这条其他信息吗？',
    
    // 侧边栏
    'sidebar.dashboard': '数据总览',
    
    // Dashboard页面
    'dashboard.title': '数据总览',
    'dashboard.description': '查看 {name} 的学习数据和表现统计',
    'dashboard.login.required': '请先登录查看学习数据',
    'dashboard.loading': '正在加载 {name} 的数据...',
    'dashboard.loading.message': '数据加载中...',
    
    // 课程统计卡片
    'dashboard.stats.average': '平均分数',
    'dashboard.stats.average.desc': '个人平均成绩',
    'dashboard.stats.pass.rate': '通过率',
    'dashboard.stats.pass.rate.desc': '课程通过率',
    'dashboard.stats.courses': '已修课程',
    'dashboard.stats.courses.desc': '总课程数量',
    'dashboard.stats.gpa': 'GPA',
    'dashboard.stats.gpa.desc': '学分绩点',
    
    // 各科成绩
    'dashboard.subjects.title': '各科成绩',
    'dashboard.subjects.description': '最近课程成绩分布',
    'dashboard.subjects.view.more': '查看更多',
    'dashboard.subjects.grade.level': '等级',
    'dashboard.subjects.no.data': '暂无成绩数据',
    'dashboard.subjects.current': '当前',
    'dashboard.subjects.average': '平均',
    
    // 课程统计
    'dashboard.course.stats.title': '课程统计',
    'dashboard.course.stats.description': '课程通过情况',
    'dashboard.course.stats.passed': '通过',
    'dashboard.course.stats.failed': '未通过',
    'dashboard.course.stats.pass.rate': '课程通过率',
    'dashboard.course.stats.summary': '已通过 {completed} / 总共 {total} 门课程',
    
    // 学期成绩趋势
    'dashboard.trends.title': '学期成绩趋势',
    'dashboard.trends.description': '各学期平均成绩变化趋势',
    'dashboard.trends.courses.count': '{count} 门课程',
    'dashboard.trends.no.data': '暂无学期数据',
    
    // 课程类型分布
    'dashboard.distribution.title': '课程类型分布',
    'dashboard.distribution.description': '不同类型课程的成绩表现',
    'dashboard.distribution.courses.count': '{count} 门',
    'dashboard.distribution.average': '平均分',
    'dashboard.distribution.no.data': '暂无课程类型数据',
    
    // 免责声明
    'disclaimer.data.accuracy': '本页面显示的平均分数、通过率、GPA等数据均为模糊计算所得，计算中只考虑必修课成绩，仅供参考和趋势分析使用。真实成绩信息请以官方教务系统为准。',
    
    // Grades页面
    'grades.title': '成绩详情',
    'grades.description': '{name} 的所有课程成绩',
    'grades.login.required': '请先登录查看学习数据',
    'grades.loading': '正在加载 {name} 的数据...',
    'grades.loading.message': '数据加载中...',
    'grades.back.to.dashboard': '返回数据总览',
    'grades.all.courses.title': '所有课程成绩',
    'grades.all.courses.description': '点击任意行查看课程详情',
    'grades.all.courses.click.hint': '点击任意行查看课程详情',
    'grades.no.data': '暂无成绩数据',
    'grades.total.courses': '共 {count} 门课程',
    'grades.table.course.name': '课程名称',
    'grades.table.semester': '学期',
    'grades.table.credit': '学分',
    'grades.table.score': '分数',


    
    // Analysis页面
    'analysis.title': '学业分析',
    'analysis.description': '深入分析您的学业表现，提供个性化改进建议',
    'analysis.loading': '正在加载学生信息',
    'analysis.efficiency.title': '学习效率',
    'analysis.efficiency.desc': '+5% 比上周',
    'analysis.target.title': '目标达成率',
    'analysis.target.desc': '+3% 比上周',
    'analysis.weak.title': '弱项科目',
    'analysis.weak.desc': '需要重点关注',
    'analysis.ranking.title': '班级排名',
    'analysis.ranking.desc': '上升3名',
    'analysis.subjects.title': '各科目分析',
    'analysis.subjects.description': '当前成绩与目标对比',
    'analysis.subjects.gap': '差距: {gap}分',
    'analysis.subjects.current': '当前: {current}',
    'analysis.subjects.target': '目标: {target}',
    'analysis.ability.title': '个人能力评估',
    'analysis.ability.description': '此数据由所有已有成绩分类加权得出',
    'analysis.ability.overall': '综合能力评分: {score}',
    'analysis.ability.logical': '逻辑思维',
    'analysis.ability.memory': '记忆能力',
    'analysis.ability.comprehension': '理解能力',
    'analysis.ability.application': '应用能力',
    'analysis.ability.innovation': '创新思维',
    'analysis.ability.expression': '表达能力',
    'analysis.tops.title': '当前专业平均GPA',
    'analysis.tops.top10': '前10%',
    'analysis.tops.top20': '前20%',
    'analysis.tops.top30': '前30%',
    'analysis.checklist.title': '打卡清单',
    'analysis.checklist.description': '记录并完成您的日常任务',
    'analysis.checklist.add.placeholder': '添加新事项...',
    'analysis.checklist.completion.rate': '完成率: {rate}%',
    'analysis.improvement.title': '改进建议',
    'analysis.improvement.description': '基于数据分析的个性化建议',
    'analysis.improvement.priority.high': '高优先级',
    'analysis.improvement.priority.medium': '中优先级',
    'analysis.improvement.estimated.time': '预计用时: {time}',
    'analysis.improvement.make.plan': '制定计划',
    'analysis.graduation.title': '毕业要求',
    'analysis.graduation.description': '完成以下要求以获得毕业资格',
    'analysis.graduation.credits': '学分要求',
    'analysis.graduation.gpa': 'GPA要求',
    'analysis.graduation.thesis': '毕业论文',
    'analysis.graduation.certificates': '证书要求',
    'analysis.graduation.completed': '已完成',
    'analysis.graduation.pending': '待完成',
    'analysis.graduation.required.credits': '总学分: {required}，已获得: {earned}',
    'analysis.graduation.required.gpa': '最低GPA: {required}，当前GPA: {current}',
    'analysis.graduation.required.thesis': '毕业论文需在毕业前完成并通过答辩',
          'analysis.graduation.required.certificates': '需获得英语四级证书或同等水平证明',
      'analysis.graduation.military': '军训学分',
      'analysis.graduation.political': '思政课程',
          'analysis.confirm.modal.title': '您的新特征值如下',
    'analysis.confirm.modal.description': '基于修改后的成绩计算得出的九个特征值',
    'analysis.confirm.modal.loading': '计算特征值中...',
    'analysis.confirm.modal.step.collecting': '📊 收集课程数据...',
    'analysis.confirm.modal.step.categorizing': '🏷️ 分类课程...',
    'analysis.confirm.modal.step.calculating': '🧮 计算加权平均...',
    'analysis.confirm.modal.step.complete': '✅ 计算完成！',
      'analysis.graduation.innovation': '创新创业学分',
      'analysis.graduation.required.military': '军训学分: {required}，已获得: {earned}',
      'analysis.graduation.required.political': '思政课程学分: {required}，已获得: {earned}',
      'analysis.graduation.required.innovation': '创新创业学分: {required}，已获得: {earned}',
      'analysis.curriculum.title': '培养方案',
      'analysis.curriculum.view.full': '下载完整培养方案',
      'analysis.curriculum.major': '专业：{major}',
      'analysis.curriculum.click.hint': '点击上方按钮查看完整培养方案',
      'analysis.curriculum.no.major': '暂无专业信息',
    
    // Curriculum页面
    'curriculum.title': '培养方案',
    'curriculum.description': '{major}专业课程列表',
    'curriculum.back': '返回',
    'curriculum.course.list': '课程列表',
    'curriculum.course.count': '共 {count} 门课程',
    'curriculum.loading': '加载中...',
    'curriculum.no.data': '暂无课程数据',
    'curriculum.table.semester': '学期',
    'curriculum.table.course.id': '课程编号',
    'curriculum.table.course.name': '课程名称',
    'curriculum.table.category': '课程类型',
    'curriculum.table.credit': '学分',
    'curriculum.table.remarks': '备注',
    
    // 海外读研/国内读研界面
    'analysis.course.scores.title': '详细课程成绩',
    'analysis.course.scores.description': '您的各门课程成绩详情（按分数降序排列）',
    'analysis.course.scores.confirm.modify': '确认修改',
    'analysis.course.scores.modify.future': '修改未来',
    'analysis.course.scores.exit.modify': '退出修改',
    'analysis.course.scores.loading': '加载课程成绩中...',
    'analysis.course.scores.no.data': '暂无课程成绩数据',
    'analysis.course.scores.table.ranking': '排名',
    'analysis.course.scores.table.semester': '学期',
    'analysis.course.scores.table.course.name': '课程名称',
    'analysis.course.scores.table.category': '课程类别',
    'analysis.course.scores.table.credit': '学分',
    'analysis.course.scores.table.score': '成绩',
    'analysis.course.scores.table.modify.score': '修改成绩',
    'analysis.course.scores.semester.format': '第{semester}学期',
    'analysis.course.scores.no.score': '暂无成绩',
    'analysis.course.scores.no.original.score': '无原始成绩',
    'analysis.course.scores.input.placeholder': '0-100',
    
    // 目标分数显示
    'analysis.target.score.loading': '加载中...',
    'analysis.target.score.no.data': '暂无目标分数数据',
    'analysis.target.score.minimum': '最低目标分数：',
    
    // 修改未来提示窗
    'analysis.edit.modal.title': '修改你的未来',
    'analysis.edit.modal.description': '让你人生拥有更多的可能性',
    
    // About页面
    'about.title': '关于BuTP',
    'about.version': '当前版本 {version}',
    
    // 雷达图相关
    'radar.modal.title': '测试字段',
    // 新增缺失的翻译键
    'analysis.login.required': '请登录查看学业分析',
    'analysis.overseas.target': '为达到{score}海外读研的目标，推荐的各科目成绩如下：',
    'analysis.domestic.target': '为达到{score}国内读研的目标，推荐的各科目成绩如下：',
    'analysis.view.all.courses': '查看所有课程数据',
    'analysis.prediction.result': '当前去向的新可能性为{current}%，另一去向的新可能性为{other}%',
    'analysis.prediction.not.started': '还未开始计算新百分比',
    'analysis.course.recommendation': '查看和修改您的课程推荐成绩',
    'analysis.calculating': '计算中...',
    'analysis.no.student.data': '该学生数据不存在',
    'analysis.overseas.title': '海外读研',
    'analysis.domestic.title': '国内读研',
    'analysis.edit.cancel': '取消编辑',
    'analysis.edit.start': '编辑',
    'analysis.edit.welcome': '欢迎进入编辑模式',
    
    // 职业模型页面
    'rolemodels.title': '职业模型',
    'rolemodels.description': '探索不同职业路径和发展机会',
    'rolemodels.possibility.employment': '就业可能性',
    'rolemodels.possibility.graduate': '升学可能性',
    'rolemodels.possibility.internship': '实习可能性',
    'rolemodels.possibility.estimate': '预估可能性',
    'rolemodels.tab.companies': '就业',
    'rolemodels.tab.schools': '升学',
    'rolemodels.tab.internships': '实习',
    'rolemodels.common.details': '查看详情',
    'rolemodels.internship.applications': '申请数',
    'rolemodels.companies.employment': '就业公司',
    'rolemodels.schools.admission': '录取学校',
    'rolemodels.internships.companies': '实习公司',
    
    // 职业模型详情页面
    'rolemodels.detail.notfound': '未找到相关信息',
    'rolemodels.detail.back': '返回',
    'rolemodels.detail.back.rolemodels': '返回职业模型',
    'rolemodels.detail.loading': '加载中...',
    'rolemodels.detail.basic.info': '基本信息',
    'rolemodels.detail.company.subtitle': '岗位详细信息',
    'rolemodels.detail.school.subtitle': '专业详细信息',
    'rolemodels.detail.internship.subtitle': '实习机会详细信息',
    'rolemodels.detail.location': '工作地点：',
    'rolemodels.detail.location.school': '地点：',
    'rolemodels.detail.rating': '评分：',
    'rolemodels.detail.consultations': '咨询次数：',
    'rolemodels.detail.consultations.times': '次',
    'rolemodels.detail.position': '职位：',
    'rolemodels.detail.duration': '时长：',
    'rolemodels.detail.major': '专业：',
    'rolemodels.detail.tuition': '学费：',
    'rolemodels.detail.scholarship': '奖学金覆盖率：',
    'rolemodels.detail.monthly.pay': '月薪：',
    'rolemodels.detail.work.time': '工作时间：',
    'rolemodels.detail.salary.title': '薪资范围',
    'rolemodels.detail.salary.entry': '初级工程师',
    'rolemodels.detail.salary.senior': '高级工程师',
    'rolemodels.detail.salary.expert': '专家级别',
    'rolemodels.detail.skills.title': '技能要求',
    'rolemodels.detail.projects.title': '项目经验',
    'rolemodels.detail.career.path.title': '职业路径',
    'rolemodels.detail.interview.points.title': '面试要点',
    'rolemodels.detail.learning.resources.title': '学习资源',
    'rolemodels.detail.competitions.title': '推荐竞赛',
    'rolemodels.detail.internships.title': '实习经历',
    'rolemodels.detail.english.scores.title': '英语成绩',
    'rolemodels.detail.description.title': '详细描述',
    'rolemodels.detail.fees.title': '费用信息',
    'rolemodels.detail.mentorship.title': '导师指导',
    'rolemodels.detail.application.tips.title': '申请技巧',
    'rolemodels.detail.skills.learn.title': '需要学习的技能',
    'rolemodels.detail.internship.benefits.title': '实习待遇',
    
    // 职业模型数据翻译 - 公司名称
    'companies.tencent': '腾讯',
    'companies.bytedance': '字节跳动',
    'companies.alibaba': '阿里巴巴',
    'companies.baidu': '百度',
    'companies.huawei': '华为',
    'companies.sensetime': '商汤科技',
    'companies.megvii': '旷视科技',
    'companies.xiaomi': '小米',
    'companies.jd': '京东',
    'companies.meituan': '美团',
    'companies.netease': '网易',
    'companies.kuaishou': '快手',
    'companies.didi': '滴滴',
    'companies.xiaohongshu': '小红书',
    'companies.bilibili': '哔哩哔哩',
    'companies.zhihu': '知乎',
    'companies.douban': '豆瓣',
    'companies.pinduoduo': '拼多多',
    'companies.oppo': 'OPPO',
    'companies.vivo': 'vivo',
    'companies.nio': '蔚来',
    'companies.ideal': '理想汽车',
    'companies.weibo': '微博',
    
    // 职业模型数据翻译 - 技能
    'skills.deeplearning': '深度学习',
    'skills.nlp': '自然语言处理',
    'skills.distributed': '分布式系统',
    'skills.machinelearning': '机器学习',
    'skills.neuralnet': '神经网络',
    'skills.datamining': '数据挖掘',
    'skills.algorithms': '算法设计',
    'skills.programming': '编程基础',
    'skills.pytorch': 'PyTorch/TensorFlow',
    'skills.cuda': 'CUDA编程',
    'skills.modeldeployment': '模型部署',
    'skills.systemdesign': '系统设计',
    'skills.frontend': '前端开发',
    'skills.backend': '后端开发',
    'skills.fullstack': '全栈开发',
    'skills.mobile': '移动开发',
    'skills.devops': '运维开发',
    'skills.dataanalysis': '数据分析',
    'skills.productmanagement': '产品管理',
    'skills.uiux': 'UI/UX设计',
    
    // 职业模型数据翻译 - 标签
    'tags.ai': '人工智能',
    'tags.bigmodel': '大模型',
    'tags.frontend': '前端',
    'tags.backend': '后端',
    'tags.fullstack': '全栈',
    'tags.mobile': '移动端',
    'tags.algorithm': '算法',
    'tags.data': '数据',
    'tags.product': '产品',
    'tags.design': '设计',
    'tags.research': '科研',
    'tags.system': '系统',
    'tags.computer': '计算机',
    
    // 职业模型数据翻译 - 学校名称
    'schools.tsinghua': '清华大学',
    'schools.peking': '北京大学',
    'schools.sjtu': '上海交通大学',
    'schools.zju': '浙江大学',
    'schools.hust': '华中科技大学',
    'schools.buaa': '北京航空航天大学',
    'schools.hit': '哈尔滨工业大学',
    'schools.fudan': '复旦大学',
    'schools.nju': '南京大学',
    'schools.ustc': '中国科学技术大学',
    'schools.xjtu': '西安交通大学',
    'schools.bupt': '北京邮电大学',
    'schools.uestc': '电子科技大学',
    'schools.xidian': '西安电子科技大学',
    'schools.seu': '东南大学',
    'schools.bit': '北京理工大学',
    'schools.dlut': '大连理工大学',
    'schools.sysu': '中山大学',
    'schools.ecnu': '华东师范大学',
    
    // 隐私条款页面
    'privacy.title': '隐私条款同意',
    'privacy.description': '请仔细阅读以下隐私政策与用户数据使用条款，同意后方可使用系统服务',
    'privacy.loading': '正在加载隐私条款内容...',
    'privacy.error.loading': '加载隐私条款失败，请刷新页面重试',
    'privacy.error.network': '网络错误，请重试',
    'privacy.error.agree': '同意失败，请重试',
    'privacy.button.agree': '我同意隐私条款',
    'privacy.button.disagree': '我不同意',
    'privacy.button.processing': '处理中...',
    'privacy.confirm.disagree': '如果您不同意隐私条款，将无法使用系统服务。确定要退出吗？',
    'privacy.hint.agree': '点击"我同意"表示您已阅读并同意上述隐私条款',
    'privacy.hint.disagree': '如果您不同意，将无法使用系统服务',
    'privacy.last.updated': '最后更新时间：{date}',
    
    // Role Models UI Labels
    'rolemodels.ui.gpa': 'GPA：',
    'rolemodels.ui.duration': '时长：',
    'rolemodels.ui.toefl': '托福：',
    'rolemodels.ui.ielts': '雅思：',
    'rolemodels.ui.etc': '等',
    'rolemodels.ui.separator': '、',
    'rolemodels.ui.gre': 'GRE：',
    
    // Position Names
    'positions.ai.engineer': '大模型工程师',
    'positions.algorithm.engineer': '算法工程师',
    'positions.frontend.engineer': '前端工程师',
    'positions.backend.engineer': '后端工程师',
    'positions.fullstack.engineer': '全栈工程师',
    'positions.mobile.engineer': '移动端工程师',
    'positions.devops.engineer': 'DevOps工程师',
    'positions.data.engineer': '数据工程师',
    'positions.product.manager': '产品经理',
    'positions.ui.ux.designer': 'UI/UX设计师',
    
    // Position Types
    'positions.ai.research': '大模型工程师(研究型)',
    'positions.ai.application': '大模型工程师(应用型)',
    'positions.algorithm.recommendation': '算法工程师(推荐系统)',
    'positions.algorithm.cv': '算法工程师(计算机视觉)',
    'positions.frontend.react': '前端工程师(React生态)',
    'positions.frontend.vue': '前端工程师(Vue生态)',
    'positions.backend.java': '后端工程师(Java生态)',
    'positions.backend.go': '后端工程师(Go云原生)',
    'positions.fullstack.startup': '全栈工程师(创业型)',
    'positions.mobile.ios': '移动端工程师(iOS原生)',
    
    // Major Names
    'majors.computer.science': '计算机科学与技术',
    'majors.electronic.engineering': '电子信息工程',
    'majors.communication.engineering': '通信工程',
    'majors.software.engineering': '软件工程',
    'majors.artificial.intelligence': '人工智能',
    'majors.data.science': '数据科学与大数据技术',
    'majors.cybersecurity': '网络空间安全',
    'majors.iot.engineering': '物联网工程',
    
    // Major Types
    'majors.cs.algorithm': '计算机科学与技术(算法方向)',
    'majors.cs.system': '计算机科学与技术(系统方向)',
    
    // Internship Categories
    'internships.tech': '技术实习',
    'internships.product': '产品实习', 
    'internships.operation': '运营实习',
    'internships.design': '设计实习',
    
    // Internship Types
    'internships.tech.backend': '技术实习生(后端开发)',
    'internships.tech.frontend': '技术实习生(前端开发)',
    'internships.tech.algorithm': '技术实习生(算法工程)',
    'internships.product.c': '产品实习生(C端产品)',
    'internships.product.b': '产品实习生(B端产品)',
    'internships.operation.content': '运营实习生(内容运营)',
    'internships.operation.data': '运营实习生(数据运营)',
    'internships.design.uiux': '设计实习生(UI/UX设计)',
    
    // Course Names
    'courses.deeplearning': '深度学习',
    'courses.nlp': '自然语言处理',
    'courses.distributed.systems': '分布式系统',
    'courses.machine.learning': '机器学习',
    'courses.neural.networks': '神经网络',
    'courses.data.mining': '数据挖掘',
    'courses.algorithm.design': '算法设计',
    'courses.operating.system': '操作系统',
    'courses.computer.networks': '计算机网络',
    'courses.database': '数据库',
    'courses.software.engineering': '软件工程',
    'courses.web.development': 'Web开发',
    'courses.mobile.development': '移动开发',
    'courses.ui.ux.design': 'UI/UX设计',
    'courses.human.computer.interaction': '人机交互',
    'courses.statistics': '统计学',
    'courses.data.structures': '数据结构',
    'courses.compiler.principles': '编译原理',
    'courses.system.architecture': '系统架构',
    'courses.cloud.computing': '云计算',
    'courses.container.technology': '容器技术',
    'courses.signal.systems': '信号与系统',
    'courses.digital.circuits': '数字电路',
    'courses.communication.principles': '通信原理',
    'courses.embedded.systems': '嵌入式系统',
    'courses.rf.circuits': '射频电路',
    'courses.fpga.design': 'FPGA设计',
    'courses.wireless.communication': '无线通信',
    'courses.network.protocols': '网络协议',
    'courses.antenna.theory': '天线理论',
    'courses.project.management': '项目管理',
    'courses.software.testing': '软件测试',
    'courses.computer.vision': '计算机视觉',
    'courses.pattern.recognition': '模式识别',
    'courses.digital.image.processing': '数字图像处理',
    'courses.reinforcement.learning': '强化学习',
    'courses.big.data.technology': '大数据技术',
    'courses.data.visualization': '数据可视化',
    'courses.cryptography': '密码学',
    'courses.network.security': '网络安全',
    'courses.system.security': '系统安全',
    'courses.web.security': 'Web安全',
    'courses.blockchain.technology': '区块链技术',
    'courses.penetration.testing': '渗透测试',
    'courses.sensor.technology': '传感器技术',
    'courses.edge.computing': '边缘计算',
    'courses.data.analysis': '数据分析',
    'courses.market.marketing': '市场营销',
    'courses.business.model': '商业模式',
    'courses.psychology': '心理学',
    'courses.visual.communication': '视觉传达',
    'courses.interaction.design': '交互设计',
    'courses.user.experience': '用户体验',
    'courses.design.thinking': '设计思维',
    'courses.art.foundation': '美术基础',
    'courses.creative.writing': '创意写作',
    'courses.news.communication': '新闻传播',
    'courses.social.media': '社交媒体',
    'courses.business.analysis': '商业分析',
    'courses.excel.sql': 'Excel/SQL',
    'courses.enterprise.management': '企业管理',
    'courses.information.systems': '信息系统',
    
    // Competition Names
    'competitions.acm': 'ACM程序设计大赛',
    'competitions.icpc': 'ICPC竞赛',
    'competitions.ai.algorithm': 'AI算法竞赛',
    'competitions.kaggle': 'KAGGLE竞赛',
    'competitions.internet.plus': '互联网+创新创业大赛',
    'competitions.ccf.programming': 'CCF编程竞赛',
    'competitions.mathematical.modeling': '数学建模竞赛',
    'competitions.tianchi.bigdata': '天池大数据竞赛',
    'competitions.electronic.design': '全国大学生电子设计竞赛',
    'competitions.challenge.cup': '挑战杯学术竞赛',
    'competitions.ic.design': '集成电路设计大赛',
    'competitions.smart.car': '智能车竞赛',
    'competitions.communication.tech': '通信技术竞赛',
    'competitions.radio.direction': '无线电测向竞赛',
    'competitions.software.design': '软件设计大赛',
    'competitions.cloud.computing': '云计算竞赛',
    'competitions.opensource.software': '开源软件竞赛',
    'competitions.hackathon': '黑客马拉松',
    'competitions.product.design': '产品设计大赛',
    'competitions.innovation.startup': '创新创业大赛',
    'competitions.business.plan': '商业计划大赛',
    'competitions.cvpr': 'CVPR竞赛',
    'competitions.imagenet': 'ImageNet竞赛',
    'competitions.cv.challenge': '计算机视觉挑战赛',
    'competitions.frontend.dev': '前端开发大赛',
    'competitions.web.design': 'Web设计竞赛',
    'competitions.vue.dev': 'Vue开发竞赛',
    'competitions.frontend.skills': '前端技能大赛',
    'competitions.opensource.contribution': '开源贡献奖',
    'competitions.system.design': '系统设计大赛',
    'competitions.cloud.native': '云原生技术竞赛',
    'competitions.system.architecture': '系统架构设计大赛',
    'competitions.fullstack.dev': '全栈开发大赛',
    'competitions.mobile.app': '移动应用开发大赛',
    'competitions.iot.app': '物联网应用竞赛',
    'competitions.smart.hardware': '智能硬件大赛',
    'competitions.operations.skills': '运维技能竞赛',
    'competitions.automation': '自动化竞赛',
    'competitions.bigdata': '大数据竞赛',
    'competitions.data.analysis': '数据分析大赛',
    'competitions.statistical.modeling': '统计建模竞赛',
    'competitions.ctf': 'CTF竞赛',
    'competitions.network.security': '网络安全大赛',
    'competitions.cryptography.tech': '密码技术竞赛',
    'competitions.design': '设计大赛',
    'competitions.ui.design': 'UI设计竞赛',
    'competitions.creative.design': '创意设计挑战赛',
    
    // Skill Names
    'skills.ai.model.training': '大模型训练',
    'skills.model.finetuning': '模型微调',
    'skills.api.development': 'API开发',
    'skills.system.integration': '系统集成',
    'skills.performance.optimization': '性能优化',
    'skills.cloud.deployment': '云平台部署',
    'skills.product.development': '产品化',
    'skills.recommendation.algorithm': '推荐算法',
    'skills.ab.testing': 'A/B测试',
    'skills.cnn': 'CNN',
    'skills.object.detection': '目标检测',
    'skills.image.segmentation': '图像分割',
    'skills.face.recognition': '人脸识别',
    'skills.opencv': 'OpenCV',
    'skills.react': 'React',
    'skills.javascript': 'JavaScript',
    'skills.typescript': 'TypeScript',
    'skills.html.css': 'HTML/CSS',
    'skills.frontend.engineering': '前端工程化',
    'skills.mobile.development': '移动端开发',
    'skills.vue3': 'Vue3',
    'skills.element.plus': 'Element Plus',
    'skills.vite': 'Vite',
    'skills.component.library': '组件库开发',
    'skills.admin.system': '中后台开发',
    'skills.java': 'Java',
    'skills.spring.boot': 'Spring Boot',
    'skills.mysql.redis': 'MySQL/Redis',
    'skills.microservices': '微服务架构',
    'skills.high.concurrency': '高并发系统设计',
    'skills.go.language': 'Go语言',
    'skills.kubernetes': 'Kubernetes',
    'skills.docker': 'Docker',
    'skills.grpc': 'gRPC',
    'skills.cloud.native': '云原生架构',
    'skills.full.stack': '前后端技术栈',
    'skills.database.design': '数据库设计',
    'skills.api.design': 'API设计',
    'skills.product.thinking': '产品思维',
    'skills.ios.development': 'iOS开发',
    'skills.swift': 'Swift',
    'skills.objective.c': 'Objective-C',
    'skills.uikit': 'UIKit',
    'skills.swiftui': 'SwiftUI',
    'skills.docker.kubernetes': 'Docker/Kubernetes',
    'skills.ci.cd': 'CI/CD',
    'skills.cloud.platform': '云平台',
    'skills.monitoring.alerting': '监控告警',
    'skills.automation.scripts': '自动化脚本',
    'skills.linux.system': 'Linux系统',
    'skills.hadoop.spark': 'Hadoop/Spark',
    'skills.sql.nosql': 'SQL/NoSQL',
    'skills.python.scala': 'Python/Scala',
    'skills.data.modeling': '数据建模',
    'skills.etl.development': 'ETL开发',
    'skills.realtime.computing': '实时计算',
    'skills.requirement.analysis': '需求分析',
    'skills.user.research': '用户研究',
    'skills.product.design': '产品设计',
    'skills.project.management': '项目管理',
    'skills.business.insight': '商业洞察',
    'skills.figma.sketch': 'Figma/Sketch',
    'skills.photoshop.illustrator': 'Photoshop/Illustrator',
    'skills.prototype.design': '原型设计',
    'skills.design.system': '设计系统',
    'skills.circuit.design': '电路设计',
    'skills.embedded.development': '嵌入式开发',
    'skills.fpga.programming': 'FPGA编程',
    'skills.pcb.design': 'PCB设计',
    'skills.signal.processing': '信号处理',
    'skills.hardware.debugging': '硬件调试',
    'skills.communication.protocols': '通信协议',
    'skills.network.planning': '网络规划',
    'skills.rf.design': 'RF设计',
    'skills.matlab.simulation': 'MATLAB仿真',
    'skills.base.station.debugging': '基站调试',
    'skills.software.architecture': '软件架构设计',
    'skills.agile.development': '敏捷开发',
    'skills.team.collaboration': '团队协作',
    'skills.code.quality': '代码质量',
    'skills.test.automation': '测试自动化',
    'skills.scientific.research': '科研能力',
    'skills.academic.writing': '学术写作',
    'skills.algorithm.optimization': '算法优化',
    'skills.mathematical.modeling': '数学建模',
    'skills.programming.implementation': '编程实现',
    'skills.innovation.thinking': '创新思维',
    'skills.data.visualization': '数据可视化',
    'skills.penetration.testing': '渗透测试',
    'skills.vulnerability.analysis': '漏洞分析',
    'skills.security.assessment': '安全评估',
    'skills.reverse.engineering': '逆向工程',
    'skills.security.programming': '安全编程',
    'skills.sensor.integration': '传感器集成',
    'skills.wireless.communication': '无线通信',
    'skills.system.integration': '系统集成',
    'skills.content.creation': '内容创作',
    'skills.user.insight': '用户洞察',
    'skills.creative.planning': '创意策划',
    'skills.social.media.operation': '社交媒体运营',
    'skills.business.understanding': '业务理解',
    'skills.system.analysis': '系统分析',
    'skills.process.design': '流程设计',
    'skills.b2b.thinking': 'B端思维',
    'skills.logical.thinking': '逻辑思维',
    'skills.report.writing': '报告撰写',
    'skills.design.thinking': '设计思维',
    'skills.learning.ability': '学习能力',
    
    // Tag Names
    'tags.recommendation.system': '推荐系统',
    'tags.application.development': '应用开发',
    'tags.productization': '产品化',
    'tags.image.processing': '图像处理',
    'tags.user.experience': '用户体验',
    'tags.component.library': '组件库',
    'tags.microservices': '微服务',
    'tags.distributed': '分布式',
    'tags.cloud.native': '云原生',
    'tags.startup': '创业',
    'tags.rapid.development': '快速开发',
    'tags.native.development': '原生开发',
    'tags.automation': '自动化',
    'tags.operations': '运维',
    'tags.big.data': '大数据',
    'tags.data.engineering': '数据工程',
    'tags.spark': 'Spark',
    'tags.hadoop': 'Hadoop',
    'tags.etl': 'ETL',
    'tags.project.management': '项目管理',
    'tags.interaction.design': '交互设计',
    'tags.visual.design': '视觉设计',
    'tags.electronics': '电子',
    'tags.embedded': '嵌入式',
    'tags.communication': '通信',
    'tags.integrated.circuit': '集成电路',
    'tags.5g': '5G',
    'tags.wireless': '无线',
    'tags.network': '网络',
    'tags.software.engineering': '软件工程',
    'tags.agile.development': '敏捷开发',
    'tags.architecture.design': '架构设计',
    'tags.competition': '竞赛',
    'tags.scientific.research': '科研',
    'tags.engineering': '工程',
    'tags.data.science': '数据科学',
    'tags.statistics': '统计',
    'tags.network.security': '网络安全',
    'tags.cryptography': '密码学',
    'tags.penetration.testing': '渗透测试',
    'tags.blockchain': '区块链',
    'tags.iot': '物联网',
    'tags.sensor': '传感器',
    'tags.edge.computing': '边缘计算',
    'tags.content': '内容',
    'tags.creativity': '创意',
    'tags.analysis': '分析',
    'tags.mentor.system': '导师制',
    'tags.technical.growth': '技术成长',
    'tags.industry.knowledge': '行业认知',
    'tags.career.development': '职业发展',
    'tags.system.thinking': '系统性思维',
    'tags.enterprise.service': '企业服务',
    'tags.work.portfolio': '作品集',
    'tags.mentor.guidance': '导师指导'
  },
  en: {
    // 登录页面
    'login.title.line1': 'Build Your Toolbox',
    'login.title.line2': 'BuTP',
    'login.description': 'Please enter your student ID hash to login',
    'login.select.label': 'Select Student Account',
    'login.select.placeholder': 'Please select a student...',
    'login.input.label': 'Enter Student ID Hash',
    'login.input.placeholder': 'Please enter 64-digit hash',
    'login.alert.input': 'Please enter your student ID hash',
    'login.alert.invalid': 'Please enter a valid student ID hash',
    'login.alert.failed': 'Login failed, please try again',
    'login.button.login': 'Login System',
    'login.button.loading': 'Logging in...',
    'login.demo.text': 'Demo System • For Learning Purpose Only',
    'login.language.switch': '切换为中文',
    'login.alert.select': 'Please select a student account',
    
    // 侧边栏
    'sidebar.profile': 'My Profile',
    'sidebar.logout': 'Logout',
    'sidebar.rolemodels': 'Career Analysis',
    'sidebar.charts': 'Charts Test',
    'sidebar.analysis': 'Academic Analysis',
    
    // Profile页面
    'profile.title': 'My Profile',
    'profile.description': 'Manage your personal information and settings',
    'profile.loading': 'Loading',
    'profile.awards.title': 'Awards & Honors',
    'profile.awards.description': 'Your achievements and honors',
    'profile.awards.add': 'Add Award',
    'profile.awards.empty': 'No information available',
    'profile.awards.form.title': 'Add Award',
    'profile.awards.form.edit': 'Edit Award',
    'profile.awards.form.name': 'Award Name',
    'profile.awards.form.organization': 'Organization/Academic Year',
    'profile.awards.form.level': 'Level',
    'profile.awards.form.level.placeholder': 'Please select level',
    'profile.awards.form.level.national': 'National',
    'profile.awards.form.level.provincial': 'Provincial',
    'profile.awards.form.level.municipal': 'Municipal',
    'profile.awards.form.level.school': 'School',
    'profile.awards.form.level.other': 'Other',
    'profile.awards.form.date': 'Award Date (Optional)',
    'profile.awards.form.date.placeholder': 'e.g.: June 2024',
    'profile.work.title': 'Work Experience',
    'profile.work.description': 'Your internship and work experience',
    'profile.work.add': 'Add Work',
    'profile.work.empty': 'No information available',
    'profile.work.form.title': 'Add Work Experience',
    'profile.work.form.edit': 'Edit Work Experience',
    'profile.work.form.position': 'Position *',
    'profile.work.form.position.placeholder': 'e.g.: Teaching Assistant Intern',
    'profile.work.form.company': 'Company/Organization *',
    'profile.work.form.company.placeholder': 'e.g.: New Oriental Education & Technology Group',
    'profile.work.form.period': 'Work Period (Optional)',
    'profile.work.form.period.placeholder': 'e.g.: July 2024 - August 2024',
    'profile.work.form.description': 'Job Description *',
    'profile.work.form.description.placeholder': 'Please briefly describe your work content and achievements',
    'profile.language.title': 'Certificates',
    'profile.language.description': 'TOEFL, IELTS, GRE and other standardized test scores',
    'profile.language.add': 'Add Score',
    'profile.language.empty': 'No information available',
    'profile.language.toefl.reading': 'Reading',
    'profile.language.toefl.listening': 'Listening',
    'profile.language.toefl.speaking': 'Speaking',
    'profile.language.toefl.writing': 'Writing',
    'profile.language.ielts.listening': 'Listening',
    'profile.language.ielts.reading': 'Reading',
    'profile.language.ielts.writing': 'Writing',
    'profile.language.ielts.speaking': 'Speaking',
    'profile.language.gre.math': 'Math',
    'profile.language.gre.verbal': 'Verbal',
    'profile.language.gre.writing': 'Writing',
    'profile.language.form.title': 'Add Score',
    'profile.language.form.edit': 'Update Score',
    'profile.language.form.type': 'Test Type',
    'profile.language.form.type.placeholder': 'Please select test type',
    'profile.language.form.total': 'Total Score',
    'profile.language.form.toefl.max': 'Max 30 points',
    'profile.language.form.ielts.example': 'e.g.: 7.5',
    'profile.language.form.gre.max': 'Max 170 points',
    'profile.language.form.gre.writing.example': 'e.g.: 4.5',
    'profile.common.cancel': 'Cancel',
    'profile.common.save': 'Save',
    'profile.common.delete': 'Delete',
    'profile.common.confirm.delete': 'Confirm Delete',
    'profile.common.confirm.delete.award': 'Are you sure you want to delete this award record?',
    'profile.common.confirm.delete.work': 'Are you sure you want to delete this work experience?',
    'profile.common.confirm.delete.toefl': 'Are you sure you want to delete the TOEFL score?',
    'profile.common.confirm.delete.ielts': 'Are you sure you want to delete the IELTS score?',
    'profile.common.confirm.delete.gre': 'Are you sure you want to delete the GRE score?',
    'profile.common.confirm.delete.note': 'This action cannot be undone.',
    
    // Other information section
    'profile.other.title': 'Other Information',
    'profile.other.description': 'Record your MBTI, hobbies, skills and other personal characteristics',
    'profile.other.add': 'Add Info',
    'profile.other.empty': 'No other information available, click the button above to add',
    'profile.other.form.title': 'Add Other Information',
    'profile.other.form.edit': 'Edit Other Information',
    'profile.other.form.category': 'Category',
    'profile.other.form.category.placeholder': 'Please select category',
    'profile.other.form.title.field': 'Title',
    'profile.other.form.title.placeholder': 'e.g.: MBTI Type, Programming Skills',
    'profile.other.form.content': 'Content',
    'profile.other.form.content.placeholder': 'e.g.: INTJ | Python, Java, React | Reading, Traveling, Photography',
    'profile.common.confirm.delete.other': 'Are you sure you want to delete this other information?',
    
    // 侧边栏
    'sidebar.dashboard': 'Dash Board',
    
    // Dashboard页面
    'dashboard.title': 'Dash Board',
    'dashboard.description': 'View {name}\'s learning data and performance statistics',
    'dashboard.login.required': 'Please log in to view learning data',
    'dashboard.loading': 'Loading {name}\'s data...',
    'dashboard.loading.message': 'Loading data...',
    
    // 课程统计卡片
    'dashboard.stats.average': 'Average Score',
    'dashboard.stats.average.desc': 'Personal average grade',
    'dashboard.stats.pass.rate': 'Pass Rate',
    'dashboard.stats.pass.rate.desc': 'Course pass rate',
    'dashboard.stats.courses': 'Courses Taken',
    'dashboard.stats.courses.desc': 'Total number of courses',
    'dashboard.stats.gpa': 'GPA',
    'dashboard.stats.gpa.desc': 'Grade Point Average',
    
    // 各科成绩
    'dashboard.subjects.title': 'Module results',
    'dashboard.subjects.description': 'Recent course grade distribution',
    'dashboard.subjects.view.more': 'View More',
    'dashboard.subjects.grade.level': 'Grade',
    'dashboard.subjects.no.data': 'No grade data available',
    'dashboard.subjects.current': 'Your score',
    'dashboard.subjects.average': 'Cohort average',
    
    // 课程统计
    'dashboard.course.stats.title': 'Course Statistics',
    'dashboard.course.stats.description': 'Course pass status',
    'dashboard.course.stats.passed': 'Passed',
    'dashboard.course.stats.failed': 'Failed',
    'dashboard.course.stats.pass.rate': 'Course Pass Rate',
    'dashboard.course.stats.summary': 'Passed {completed} / Total {total} courses',
    
    // 学期成绩趋势
    'dashboard.trends.title': 'Semester based performance trend',
    'dashboard.trends.description': 'Average grade changes by semester',
    'dashboard.trends.courses.count': '{count} courses',
    'dashboard.trends.no.data': 'No semester data available',
    
    // 课程类型分布
    'dashboard.distribution.title': 'Module performance by category',
    'dashboard.distribution.description': 'Performance by different course types',
    'dashboard.distribution.courses.count': '{count} courses',
    'dashboard.distribution.average': 'Average',
    'dashboard.distribution.no.data': 'No course type data available',
    
    // 免责声明
    'disclaimer.data.accuracy': 'The average scores, pass rates, GPA and other data displayed on this page are obtained through fuzzy calculations and are for reference and trend analysis only. Please refer to the official academic system for accurate grade information.',
    
    // Grades页面
    'grades.title': 'Grade Details',
    'grades.description': 'All course grades for {name}',
    'grades.login.required': 'Please log in to view learning data',
    'grades.loading': 'Loading {name}\'s data...',
    'grades.loading.message': 'Loading data...',
    'grades.back.to.dashboard': 'Back to Dashboard',
    'grades.all.courses.title': 'All Course Grades',
    'grades.all.courses.description': 'Detailed course grade list (sorted by credit from high to low)',
    'grades.all.courses.click.hint': 'Click on a course to view detailed information',
    'grades.table.course.name': 'Course Name',
    'grades.table.credit': 'Credit',
    'grades.table.score': 'Score',
    'grades.no.data': 'No grade data available',
    'grades.total.courses': 'Total {count} courses',
    'grades.table.semester': 'Semester',


    
    // Analysis页面
    'analysis.title': 'Academic Analysis',
    'analysis.description': 'In-depth analysis of your academic performance with personalized improvement suggestions',
    'analysis.loading': 'Loading',
    'analysis.efficiency.title': 'Learning Efficiency',
    'analysis.efficiency.desc': '+5% from last week',
    'analysis.target.title': 'Goal Achievement',
    'analysis.target.desc': '+3% from last week',
    'analysis.weak.title': 'Weak Subjects',
    'analysis.weak.desc': 'Need focused attention',
    'analysis.ranking.title': 'Class Ranking',
    'analysis.ranking.desc': 'Up 3 places',
    'analysis.subjects.title': 'Subject Analysis',
    'analysis.subjects.description': 'Current vs target performance comparison',
    'analysis.subjects.gap': 'Gap: {gap} points',
    'analysis.subjects.current': 'Current: {current}',
    'analysis.subjects.target': 'Target: {target}',
    'analysis.ability.title': 'Personal Ability Assessment',
    'analysis.ability.description': 'Comprehensive ability evaluation',
    'analysis.ability.overall': 'Overall ability score: {score}',
    'analysis.ability.logical': 'Logical Thinking',
    'analysis.ability.memory': 'Memory Ability',
    'analysis.ability.comprehension': 'Comprehension Ability',
    'analysis.ability.application': 'Application Ability',
    'analysis.ability.innovation': 'Innovation Thinking',
    'analysis.ability.expression': 'Expression Ability',
    'analysis.tops.title': 'Major Average Score',
    'analysis.tops.top10': 'Top 10%',
    'analysis.tops.top20': 'Top 20%',
    'analysis.tops.top30': 'Top 30%',
    'analysis.checklist.title': 'Daily Checklist',
    'analysis.checklist.description': 'Track and complete your daily tasks',
    'analysis.checklist.add.placeholder': 'Add new item...',
    'analysis.checklist.completion.rate': 'Completion rate: {rate}%',
    'analysis.improvement.title': 'Improvement Suggestions',
    'analysis.improvement.description': 'Personalized recommendations based on data analysis',
    'analysis.improvement.priority.high': 'High Priority',
    'analysis.improvement.priority.medium': 'Medium Priority',
    'analysis.improvement.estimated.time': 'Estimated time: {time}',
    'analysis.improvement.make.plan': 'Make Plan',
    'analysis.graduation.title': 'Graduation Requirements',
    'analysis.graduation.description': 'Complete the following requirements to obtain graduation eligibility',
    'analysis.graduation.credits': 'Credit Requirements',
    'analysis.graduation.gpa': 'GPA Requirements',
    'analysis.graduation.thesis': 'Thesis',
    'analysis.graduation.certificates': 'Certificate Requirements',
    'analysis.graduation.completed': 'Completed',
    'analysis.graduation.pending': 'Pending',
    'analysis.graduation.required.credits': 'Total Credits: {required}, Earned: {earned}',
    'analysis.graduation.required.gpa': 'Minimum GPA: {required}, Current GPA: {current}',
    'analysis.graduation.required.thesis': 'Thesis must be completed and defended before graduation',
    'analysis.graduation.required.certificates': 'Must obtain CET-4 certificate or equivalent proof',
    'analysis.graduation.military': 'Military Training Credits',
    'analysis.graduation.political': 'Political Education',
    'analysis.graduation.innovation': 'Innovation Credits',
    'analysis.graduation.required.military': 'Military training credits: {required}, earned: {earned}',
    'analysis.graduation.required.political': 'Political education credits: {required}, earned: {earned}',
    'analysis.graduation.required.innovation': 'Innovation credits: {required}, earned: {earned}',
    'analysis.confirm.modal.title': 'Your New Feature Values',
    'analysis.confirm.modal.description': 'Nine feature values calculated based on modified grades',
    'analysis.confirm.modal.loading': 'Calculating feature values...',
    'analysis.confirm.modal.step.collecting': '📊 Collecting course data...',
    'analysis.confirm.modal.step.categorizing': '🏷️ Categorizing courses...',
    'analysis.confirm.modal.step.calculating': '🧮 Calculating weighted average...',
    'analysis.confirm.modal.step.complete': '✅ Calculation complete!',
    'analysis.curriculum.title': 'Curriculum',
    'analysis.curriculum.view.full': 'Download Full Curriculum',
    'analysis.curriculum.major': 'Major: {major}',
    'analysis.curriculum.click.hint': 'Click the button above to view the full curriculum',
    'analysis.curriculum.no.major': 'No major information available',
    
    // Curriculum页面
    'curriculum.title': 'Curriculum',
    'curriculum.description': '{major} Major Course List',
    'curriculum.back': 'Back',
    'curriculum.course.list': 'Course List',
    'curriculum.course.count': 'Total {count} courses',
    'curriculum.loading': 'Loading...',
    'curriculum.no.data': 'No course data available',
    'curriculum.table.semester': 'Semester',
    'curriculum.table.course.id': 'Course ID',
    'curriculum.table.course.name': 'Course Name',
    'curriculum.table.category': 'Course Type',
    'curriculum.table.credit': 'Credit',
    'curriculum.table.remarks': 'Remarks',
    
    // 海外读研/国内读研界面
    'analysis.course.scores.title': 'Detailed Course Scores',
    'analysis.course.scores.description': 'Your course score details (sorted by score in descending order)',
    'analysis.course.scores.confirm.modify': 'Confirm Modification',
    'analysis.course.scores.modify.future': 'Modify Future',
    'analysis.course.scores.exit.modify': 'Exit Modification',
    'analysis.course.scores.loading': 'Loading course scores...',
    'analysis.course.scores.no.data': 'No course score data available',
    'analysis.course.scores.table.ranking': 'Ranking',
    'analysis.course.scores.table.semester': 'Semester',
    'analysis.course.scores.table.course.name': 'Course Name',
    'analysis.course.scores.table.category': 'Course Category',
    'analysis.course.scores.table.credit': 'Credit',
    'analysis.course.scores.table.score': 'Score',
    'analysis.course.scores.table.modify.score': 'Modify Score',
    'analysis.course.scores.semester.format': 'Semester {semester}',
    'analysis.course.scores.no.score': 'No Score',
    'analysis.course.scores.no.original.score': 'No Original Score',
    'analysis.course.scores.input.placeholder': '0-100',
    
    // 目标分数显示
    'analysis.target.score.loading': 'Loading...',
    'analysis.target.score.no.data': 'No target score data available',
    'analysis.target.score.minimum': 'To achieve this goal, the minimum average score is',
    
    // 修改未来提示窗
    'analysis.edit.modal.title': 'Modify Your Future',
    'analysis.edit.modal.description': 'Give your life more possibilities',
    
    // About页面
    'about.title': 'About BuTP',
    'about.version': 'Version {version}',
    
    // 雷达图相关
    'radar.modal.title': 'test content',
    // 新增缺失的翻译键
    'analysis.login.required': 'Please log in to view academic analysis',
    'analysis.overseas.target': 'To achieve the {score} overseas study goal, the recommended course scores are as follows:',
    'analysis.domestic.target': 'To achieve the {score} domestic study goal, the recommended course scores are as follows:',
    'analysis.view.all.courses': 'View All Course Data',
    'analysis.prediction.result': 'Current path new possibility: {current}%, other path new possibility: {other}%',
    'analysis.prediction.not.started': 'New percentage calculation not started yet',
    'analysis.course.recommendation': 'View and modify your recommended course scores',
    'analysis.calculating': 'Calculating...',
    'analysis.no.student.data': 'Student data does not exist',
    'analysis.overseas.title': 'Overseas Study',
    'analysis.domestic.title': 'Domestic Study',
    'analysis.edit.cancel': 'Cancel Edit',
    'analysis.edit.start': 'Edit',
    'analysis.edit.welcome': 'Welcome to Edit Mode',
    
    // Role Models Page
    'rolemodels.title': 'Career Models',
    'rolemodels.description': 'Explore different career paths and development opportunities',
    'rolemodels.possibility.employment': 'Employment Possibility',
    'rolemodels.possibility.graduate': 'Graduate School Possibility',
    'rolemodels.possibility.internship': 'Internship Possibility',
    'rolemodels.possibility.estimate': 'Estimated Possibility',
    'rolemodels.tab.companies': 'Employment',
    'rolemodels.tab.schools': 'Graduate Study',
    'rolemodels.tab.internships': 'Internships',
    'rolemodels.common.details': 'View Details',
    'rolemodels.internship.applications': 'Applications',
    'rolemodels.companies.employment': 'Employment Companies',
    'rolemodels.schools.admission': 'Admission Schools',
    'rolemodels.internships.companies': 'Internship Companies',
    
    // Role Models Detail Page
    'rolemodels.detail.notfound': 'No relevant information found',
    'rolemodels.detail.back': 'Back',
    'rolemodels.detail.back.rolemodels': 'Back to Career Models',
    'rolemodels.detail.loading': 'Loading...',
    'rolemodels.detail.basic.info': 'Basic Information',
    'rolemodels.detail.company.subtitle': 'Position Details',
    'rolemodels.detail.school.subtitle': 'Major Details',
    'rolemodels.detail.internship.subtitle': 'Internship Opportunity Details',
    'rolemodels.detail.location': 'Work Location: ',
    'rolemodels.detail.location.school': 'Location: ',
    'rolemodels.detail.rating': 'Rating: ',
    'rolemodels.detail.consultations': 'Consultations: ',
    'rolemodels.detail.consultations.times': ' times',
    'rolemodels.detail.position': 'Position: ',
    'rolemodels.detail.duration': 'Duration: ',
    'rolemodels.detail.major': 'Major: ',
    'rolemodels.detail.tuition': 'Tuition: ',
    'rolemodels.detail.scholarship': 'Scholarship Rate: ',
    'rolemodels.detail.monthly.pay': 'Monthly Pay: ',
    'rolemodels.detail.work.time': 'Work Time: ',
    'rolemodels.detail.salary.title': 'Salary Range',
    'rolemodels.detail.salary.entry': 'Entry Level',
    'rolemodels.detail.salary.senior': 'Senior Level',
    'rolemodels.detail.salary.expert': 'Expert Level',
    'rolemodels.detail.skills.title': 'Required Skills',
    'rolemodels.detail.projects.title': 'Project Experience',
    'rolemodels.detail.career.path.title': 'Career Path',
    'rolemodels.detail.interview.points.title': 'Interview Points',
    'rolemodels.detail.learning.resources.title': 'Learning Resources',
    'rolemodels.detail.competitions.title': 'Recommended Competitions',
    'rolemodels.detail.internships.title': 'Internship Experience',
    'rolemodels.detail.english.scores.title': 'English Scores',
    'rolemodels.detail.description.title': 'Detailed Description',
    'rolemodels.detail.fees.title': 'Fee Information',
    'rolemodels.detail.mentorship.title': 'Mentorship',
    'rolemodels.detail.application.tips.title': 'Application Tips',
    'rolemodels.detail.skills.learn.title': 'Skills to Learn',
    'rolemodels.detail.internship.benefits.title': 'Internship Benefits',
    
    // Role Models Data Translations - Companies
    'companies.tencent': 'Tencent',
    'companies.bytedance': 'ByteDance',
    'companies.alibaba': 'Alibaba',
    'companies.baidu': 'Baidu',
    'companies.huawei': 'Huawei',
    'companies.sensetime': 'SenseTime',
    'companies.megvii': 'Megvii',
    'companies.xiaomi': 'Xiaomi',
    'companies.jd': 'JD.com',
    'companies.meituan': 'Meituan',
    'companies.netease': 'NetEase',
    'companies.kuaishou': 'Kuaishou',
    'companies.didi': 'Didi',
    'companies.xiaohongshu': 'Xiaohongshu',
    'companies.bilibili': 'Bilibili',
    'companies.zhihu': 'Zhihu',
    'companies.douban': 'Douban',
    'companies.pinduoduo': 'Pinduoduo',
    'companies.oppo': 'OPPO',
    'companies.vivo': 'Vivo',
    'companies.nio': 'NIO',
    'companies.ideal': 'Li Auto',
    'companies.weibo': 'Weibo',
    
    // Role Models Data Translations - Skills
    'skills.deeplearning': 'Deep Learning',
    'skills.nlp': 'Natural Language Processing',
    'skills.distributed': 'Distributed Systems',
    'skills.machinelearning': 'Machine Learning',
    'skills.neuralnet': 'Neural Networks',
    'skills.datamining': 'Data Mining',
    'skills.algorithms': 'Algorithm Design',
    'skills.programming': 'Programming',
    'skills.pytorch': 'PyTorch/TensorFlow',
    'skills.cuda': 'CUDA Programming',
    'skills.modeldeployment': 'Model Deployment',
    'skills.systemdesign': 'System Design',
    'skills.frontend': 'Frontend Development',
    'skills.backend': 'Backend Development',
    'skills.fullstack': 'Full Stack Development',
    'skills.mobile': 'Mobile Development',
    'skills.devops': 'DevOps',
    'skills.dataanalysis': 'Data Analysis',
    'skills.productmanagement': 'Product Management',
    'skills.uiux': 'UI/UX Design',
    
    // Role Models Data Translations - Tags
    'tags.ai': 'Artificial Intelligence',
    'tags.bigmodel': 'Large Language Model',
    'tags.frontend': 'Frontend',
    'tags.backend': 'Backend',
    'tags.fullstack': 'Full Stack',
    'tags.mobile': 'Mobile',
    'tags.algorithm': 'Algorithm',
    'tags.data': 'Data',
    'tags.product': 'Product',
    'tags.design': 'Design',
    'tags.research': 'Research',
    'tags.system': 'System',
    'tags.computer': 'Computer Science',
    
    // Role Models Data Translations - Schools
    'schools.tsinghua': 'Tsinghua University',
    'schools.peking': 'Peking University',
    'schools.sjtu': 'Shanghai Jiao Tong University',
    'schools.zju': 'Zhejiang University',
    'schools.hust': 'Huazhong University of Science and Technology',
    'schools.buaa': 'Beijing University of Aeronautics and Astronautics',
    'schools.hit': 'Harbin Institute of Technology',
    'schools.fudan': 'Fudan University',
    'schools.nju': 'Nanjing University',
    'schools.ustc': 'University of Science and Technology of China',
    'schools.xjtu': 'Xi\'an Jiaotong University',
    'schools.bupt': 'Beijing University of Posts and Telecommunications',
    'schools.uestc': 'University of Electronic Science and Technology of China',
    'schools.xidian': 'Xidian University',
    'schools.seu': 'Southeast University',
    'schools.bit': 'Beijing Institute of Technology',
    'schools.dlut': 'Dalian University of Technology',
    'schools.sysu': 'Sun Yat-sen University',
    'schools.ecnu': 'East China Normal University',
    
    // Role Models UI Labels
    'rolemodels.ui.gpa': 'GPA: ',
    'rolemodels.ui.duration': 'Duration: ',
    'rolemodels.ui.toefl': 'TOEFL: ',
    'rolemodels.ui.ielts': 'IELTS: ',
    'rolemodels.ui.etc': ' etc.',
    'rolemodels.ui.separator': ', ',
    'rolemodels.ui.gre': 'GRE: ',
    
    // Position Names
    'positions.ai.engineer': 'AI Engineer',
    'positions.algorithm.engineer': 'Algorithm Engineer',
    'positions.frontend.engineer': 'Frontend Engineer',
    'positions.backend.engineer': 'Backend Engineer',
    'positions.fullstack.engineer': 'Full Stack Engineer',
    'positions.mobile.engineer': 'Mobile Engineer',
    'positions.devops.engineer': 'DevOps Engineer',
    'positions.data.engineer': 'Data Engineer',
    'positions.product.manager': 'Product Manager',
    'positions.ui.ux.designer': 'UI/UX Designer',
    
    // Position Types
    'positions.ai.research': 'AI Engineer (Research)',
    'positions.ai.application': 'AI Engineer (Application)',
    'positions.algorithm.recommendation': 'Algorithm Engineer (Recommendation)',
    'positions.algorithm.cv': 'Algorithm Engineer (Computer Vision)',
    'positions.frontend.react': 'Frontend Engineer (React)',
    'positions.frontend.vue': 'Frontend Engineer (Vue)',
    'positions.backend.java': 'Backend Engineer (Java)',
    'positions.backend.go': 'Backend Engineer (Go)',
    'positions.fullstack.startup': 'Full Stack Engineer (Startup)',
    'positions.mobile.ios': 'Mobile Engineer (iOS)',
    
    // Major Names
    'majors.computer.science': 'Computer Science and Technology',
    'majors.electronic.engineering': 'Electronic Information Engineering',
    'majors.communication.engineering': 'Communication Engineering',
    'majors.software.engineering': 'Software Engineering',
    'majors.artificial.intelligence': 'Artificial Intelligence',
    'majors.data.science': 'Data Science and Big Data Technology',
    'majors.cybersecurity': 'Cyberspace Security',
    'majors.iot.engineering': 'Internet of Things Engineering',
    
    // Major Types
    'majors.cs.algorithm': 'Computer Science (Algorithm)',
    'majors.cs.system': 'Computer Science (System)',
    
    // Internship Categories
    'internships.tech': 'Technical Internship',
    'internships.product': 'Product Internship', 
    'internships.operation': 'Operations Internship',
    'internships.design': 'Design Internship',
    
    // Internship Types
    'internships.tech.backend': 'Technical Intern (Backend)',
    'internships.tech.frontend': 'Technical Intern (Frontend)',
    'internships.tech.algorithm': 'Technical Intern (Algorithm)',
    'internships.product.c': 'Product Intern (C-end)',
    'internships.product.b': 'Product Intern (B-end)',
    'internships.operation.content': 'Operations Intern (Content)',
    'internships.operation.data': 'Operations Intern (Data)',
    'internships.design.uiux': 'Design Intern (UI/UX)',
    
    // Course Names
    'courses.deeplearning': 'Deep Learning',
    'courses.nlp': 'Natural Language Processing',
    'courses.distributed.systems': 'Distributed Systems',
    'courses.machine.learning': 'Machine Learning',
    'courses.neural.networks': 'Neural Networks',
    'courses.data.mining': 'Data Mining',
    'courses.algorithm.design': 'Algorithm Design',
    'courses.operating.system': 'Operating System',
    'courses.computer.networks': 'Computer Networks',
    'courses.database': 'Database',
    'courses.software.engineering': 'Software Engineering',
    'courses.web.development': 'Web Development',
    'courses.mobile.development': 'Mobile Development',
    'courses.ui.ux.design': 'UI/UX Design',
    'courses.human.computer.interaction': 'Human-Computer Interaction',
    'courses.statistics': 'Statistics',
    'courses.data.structures': 'Data Structures',
    'courses.compiler.principles': 'Compiler Principles',
    'courses.system.architecture': 'System Architecture',
    'courses.cloud.computing': 'Cloud Computing',
    'courses.container.technology': 'Container Technology',
    'courses.signal.systems': 'Signal and Systems',
    'courses.digital.circuits': 'Digital Circuits',
    'courses.communication.principles': 'Communication Principles',
    'courses.embedded.systems': 'Embedded Systems',
    'courses.rf.circuits': 'RF Circuits',
    'courses.fpga.design': 'FPGA Design',
    'courses.wireless.communication': 'Wireless Communication',
    'courses.network.protocols': 'Network Protocols',
    'courses.antenna.theory': 'Antenna Theory',
    'courses.project.management': 'Project Management',
    'courses.software.testing': 'Software Testing',
    'courses.computer.vision': 'Computer Vision',
    'courses.pattern.recognition': 'Pattern Recognition',
    'courses.digital.image.processing': 'Digital Image Processing',
    'courses.reinforcement.learning': 'Reinforcement Learning',
    'courses.big.data.technology': 'Big Data Technology',
    'courses.data.visualization': 'Data Visualization',
    'courses.cryptography': 'Cryptography',
    'courses.network.security': 'Network Security',
    'courses.system.security': 'System Security',
    'courses.web.security': 'Web Security',
    'courses.blockchain.technology': 'Blockchain Technology',
    'courses.penetration.testing': 'Penetration Testing',
    'courses.sensor.technology': 'Sensor Technology',
    'courses.edge.computing': 'Edge Computing',
    'courses.data.analysis': 'Data Analysis',
    'courses.market.marketing': 'Market Marketing',
    'courses.business.model': 'Business Model',
    'courses.psychology': 'Psychology',
    'courses.visual.communication': 'Visual Communication',
    'courses.interaction.design': 'Interaction Design',
    'courses.user.experience': 'User Experience',
    'courses.design.thinking': 'Design Thinking',
    'courses.art.foundation': 'Art Foundation',
    'courses.creative.writing': 'Creative Writing',
    'courses.news.communication': 'News Communication',
    'courses.social.media': 'Social Media',
    'courses.business.analysis': 'Business Analysis',
    'courses.excel.sql': 'Excel/SQL',
    'courses.enterprise.management': 'Enterprise Management',
    'courses.information.systems': 'Information Systems',
    
    // Competition Names
    'competitions.acm': 'ACM Programming Contest',
    'competitions.icpc': 'ICPC Contest',
    'competitions.ai.algorithm': 'AI Algorithm Contest',
    'competitions.kaggle': 'KAGGLE Contest',
    'competitions.internet.plus': 'Internet+ Innovation Contest',
    'competitions.ccf.programming': 'CCF Programming Contest',
    'competitions.mathematical.modeling': 'Mathematical Modeling Contest',
    'competitions.tianchi.bigdata': 'Tianchi Big Data Contest',
    'competitions.electronic.design': 'Electronic Design Contest',
    'competitions.challenge.cup': 'Challenge Cup Academic Contest',
    'competitions.ic.design': 'IC Design Contest',
    'competitions.smart.car': 'Smart Car Contest',
    'competitions.communication.tech': 'Communication Technology Contest',
    'competitions.radio.direction': 'Radio Direction Finding Contest',
    'competitions.software.design': 'Software Design Contest',
    'competitions.cloud.computing': 'Cloud Computing Contest',
    'competitions.opensource.software': 'Open Source Software Contest',
    'competitions.hackathon': 'Hackathon',
    'competitions.product.design': 'Product Design Contest',
    'competitions.innovation.startup': 'Innovation and Startup Contest',
    'competitions.business.plan': 'Business Plan Contest',
    'competitions.cvpr': 'CVPR Contest',
    'competitions.imagenet': 'ImageNet Contest',
    'competitions.cv.challenge': 'Computer Vision Challenge',
    'competitions.frontend.dev': 'Frontend Development Contest',
    'competitions.web.design': 'Web Design Contest',
    'competitions.vue.dev': 'Vue Development Contest',
    'competitions.frontend.skills': 'Frontend Skills Contest',
    'competitions.opensource.contribution': 'Open Source Contribution Award',
    'competitions.system.design': 'System Design Contest',
    'competitions.cloud.native': 'Cloud Native Technology Contest',
    'competitions.system.architecture': 'System Architecture Design Contest',
    'competitions.fullstack.dev': 'Full Stack Development Contest',
    'competitions.mobile.app': 'Mobile App Development Contest',
    'competitions.iot.app': 'IoT Application Contest',
    'competitions.smart.hardware': 'Smart Hardware Contest',
    'competitions.operations.skills': 'Operations Skills Contest',
    'competitions.automation': 'Automation Contest',
    'competitions.bigdata': 'Big Data Contest',
    'competitions.data.analysis': 'Data Analysis Contest',
    'competitions.statistical.modeling': 'Statistical Modeling Contest',
    'competitions.ctf': 'CTF Contest',
    'competitions.network.security': 'Network Security Contest',
    'competitions.cryptography.tech': 'Cryptography Technology Contest',
    'competitions.design': 'Design Contest',
    'competitions.ui.design': 'UI Design Contest',
    'competitions.creative.design': 'Creative Design Challenge',
    
    // Skill Names
    'skills.ai.model.training': 'AI Model Training',
    'skills.model.finetuning': 'Model Fine-tuning',
    'skills.api.development': 'API Development',
    'skills.system.integration': 'System Integration',
    'skills.performance.optimization': 'Performance Optimization',
    'skills.cloud.deployment': 'Cloud Platform Deployment',
    'skills.product.development': 'Product Development',
    'skills.recommendation.algorithm': 'Recommendation Algorithm',
    'skills.ab.testing': 'A/B Testing',
    'skills.cnn': 'CNN',
    'skills.object.detection': 'Object Detection',
    'skills.image.segmentation': 'Image Segmentation',
    'skills.face.recognition': 'Face Recognition',
    'skills.opencv': 'OpenCV',
    'skills.react': 'React',
    'skills.javascript': 'JavaScript',
    'skills.typescript': 'TypeScript',
    'skills.html.css': 'HTML/CSS',
    'skills.frontend.engineering': 'Frontend Engineering',
    'skills.mobile.development': 'Mobile Development',
    'skills.vue3': 'Vue3',
    'skills.element.plus': 'Element Plus',
    'skills.vite': 'Vite',
    'skills.component.library': 'Component Library Development',
    'skills.admin.system': 'Admin System Development',
    'skills.java': 'Java',
    'skills.spring.boot': 'Spring Boot',
    'skills.mysql.redis': 'MySQL/Redis',
    'skills.microservices': 'Microservices Architecture',
    'skills.high.concurrency': 'High Concurrency System Design',
    'skills.go.language': 'Go Language',
    'skills.kubernetes': 'Kubernetes',
    'skills.docker': 'Docker',
    'skills.grpc': 'gRPC',
    'skills.cloud.native': 'Cloud Native Architecture',
    'skills.full.stack': 'Full Stack Technology',
    'skills.database.design': 'Database Design',
    'skills.api.design': 'API Design',
    'skills.product.thinking': 'Product Thinking',
    'skills.ios.development': 'iOS Development',
    'skills.swift': 'Swift',
    'skills.objective.c': 'Objective-C',
    'skills.uikit': 'UIKit',
    'skills.swiftui': 'SwiftUI',
    'skills.docker.kubernetes': 'Docker/Kubernetes',
    'skills.ci.cd': 'CI/CD',
    'skills.cloud.platform': 'Cloud Platform',
    'skills.monitoring.alerting': 'Monitoring and Alerting',
    'skills.automation.scripts': 'Automation Scripts',
    'skills.linux.system': 'Linux System',
    'skills.hadoop.spark': 'Hadoop/Spark',
    'skills.sql.nosql': 'SQL/NoSQL',
    'skills.python.scala': 'Python/Scala',
    'skills.data.modeling': 'Data Modeling',
    'skills.etl.development': 'ETL Development',
    'skills.realtime.computing': 'Real-time Computing',
    'skills.requirement.analysis': 'Requirement Analysis',
    'skills.user.research': 'User Research',
    'skills.product.design': 'Product Design',
    'skills.project.management': 'Project Management',
    'skills.business.insight': 'Business Insight',
    'skills.figma.sketch': 'Figma/Sketch',
    'skills.photoshop.illustrator': 'Photoshop/Illustrator',
    'skills.prototype.design': 'Prototype Design',
    'skills.design.system': 'Design System',
    'skills.circuit.design': 'Circuit Design',
    'skills.embedded.development': 'Embedded Development',
    'skills.fpga.programming': 'FPGA Programming',
    'skills.pcb.design': 'PCB Design',
    'skills.signal.processing': 'Signal Processing',
    'skills.hardware.debugging': 'Hardware Debugging',
    'skills.communication.protocols': 'Communication Protocols',
    'skills.network.planning': 'Network Planning',
    'skills.rf.design': 'RF Design',
    'skills.matlab.simulation': 'MATLAB Simulation',
    'skills.base.station.debugging': 'Base Station Debugging',
    'skills.software.architecture': 'Software Architecture Design',
    'skills.agile.development': 'Agile Development',
    'skills.team.collaboration': 'Team Collaboration',
    'skills.code.quality': 'Code Quality',
    'skills.test.automation': 'Test Automation',
    'skills.scientific.research': 'Scientific Research Ability',
    'skills.academic.writing': 'Academic Writing',
    'skills.algorithm.optimization': 'Algorithm Optimization',
    'skills.mathematical.modeling': 'Mathematical Modeling',
    'skills.programming.implementation': 'Programming Implementation',
    'skills.innovation.thinking': 'Innovation Thinking',
    'skills.data.visualization': 'Data Visualization',
    'skills.penetration.testing': 'Penetration Testing',
    'skills.vulnerability.analysis': 'Vulnerability Analysis',
    'skills.security.assessment': 'Security Assessment',
    'skills.reverse.engineering': 'Reverse Engineering',
    'skills.security.programming': 'Security Programming',
    'skills.sensor.integration': 'Sensor Integration',
    'skills.wireless.communication': 'Wireless Communication',
    'skills.system.integration': 'System Integration',
    'skills.content.creation': 'Content Creation',
    'skills.user.insight': 'User Insight',
    'skills.creative.planning': 'Creative Planning',
    'skills.social.media.operation': 'Social Media Operation',
    'skills.business.understanding': 'Business Understanding',
    'skills.system.analysis': 'System Analysis',
    'skills.process.design': 'Process Design',
    'skills.b2b.thinking': 'B2B Thinking',
    'skills.logical.thinking': 'Logical Thinking',
    'skills.report.writing': 'Report Writing',
    'skills.design.thinking': 'Design Thinking',
    'skills.learning.ability': 'Learning Ability',
    
    // Tag Names
    'tags.recommendation.system': 'Recommendation System',
    'tags.application.development': 'Application Development',
    'tags.productization': 'Productization',
    'tags.image.processing': 'Image Processing',
    'tags.user.experience': 'User Experience',
    'tags.component.library': 'Component Library',
    'tags.microservices': 'Microservices',
    'tags.distributed': 'Distributed',
    'tags.cloud.native': 'Cloud Native',
    'tags.startup': 'Startup',
    'tags.rapid.development': 'Rapid Development',
    'tags.native.development': 'Native Development',
    'tags.automation': 'Automation',
    'tags.operations': 'Operations',
    'tags.big.data': 'Big Data',
    'tags.data.engineering': 'Data Engineering',
    'tags.spark': 'Spark',
    'tags.hadoop': 'Hadoop',
    'tags.etl': 'ETL',
    'tags.project.management': 'Project Management',
    'tags.interaction.design': 'Interaction Design',
    'tags.visual.design': 'Visual Design',
    'tags.electronics': 'Electronics',
    'tags.embedded': 'Embedded',
    'tags.communication': 'Communication',
    'tags.integrated.circuit': 'Integrated Circuit',
    'tags.5g': '5G',
    'tags.wireless': 'Wireless',
    'tags.network': 'Network',
    'tags.software.engineering': 'Software Engineering',
    'tags.agile.development': 'Agile Development',
    'tags.architecture.design': 'Architecture Design',
    'tags.competition': 'Competition',
    'tags.scientific.research': 'Scientific Research',
    'tags.engineering': 'Engineering',
    'tags.data.science': 'Data Science',
    'tags.statistics': 'Statistics',
    'tags.network.security': 'Network Security',
    'tags.cryptography': 'Cryptography',
    'tags.penetration.testing': 'Penetration Testing',
    'tags.blockchain': 'Blockchain',
    'tags.iot': 'Internet of Things',
    'tags.sensor': 'Sensor',
    'tags.edge.computing': 'Edge Computing',
    'tags.content': 'Content',
    'tags.creativity': 'Creativity',
    'tags.analysis': 'Analysis',
    'tags.mentor.system': 'Mentor System',
    'tags.technical.growth': 'Technical Growth',
    'tags.industry.knowledge': 'Industry Knowledge',
    'tags.career.development': 'Career Development',
    'tags.system.thinking': 'System Thinking',
    'tags.enterprise.service': 'Enterprise Service',
    'tags.work.portfolio': 'Work Portfolio',
    'tags.mentor.guidance': 'Mentor Guidance',
    
    // Privacy Agreement Page
    'privacy.title': 'Privacy Agreement',
    'privacy.description': 'Please carefully read the following privacy policy and user data usage terms. You must agree to use the system services.',
    'privacy.loading': 'Loading privacy policy content...',
    'privacy.error.loading': 'Failed to load privacy policy, please refresh the page and try again',
    'privacy.error.network': 'Network error, please try again',
    'privacy.error.agree': 'Agreement failed, please try again',
    'privacy.button.agree': 'I Agree to Privacy Policy',
    'privacy.button.disagree': 'I Disagree',
    'privacy.button.processing': 'Processing...',
    'privacy.confirm.disagree': 'If you disagree with the privacy policy, you will not be able to use the system services. Are you sure you want to exit?',
    'privacy.hint.agree': 'Clicking "I Agree" means you have read and agreed to the above privacy policy',
    'privacy.hint.disagree': 'If you disagree, you will not be able to use the system services',
    'privacy.last.updated': 'Last updated: {date}'
  }
}

// 语言提供者组件
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh')

  // 从 localStorage 读取语言设置
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // 保存语言设置到 localStorage
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  // 翻译函数
  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key
    
    // 如果有参数，进行替换
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(new RegExp(`{${paramKey}}`, 'g'), String(paramValue))
      })
    }
    
    return translation
  }

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: handleSetLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

// 自定义Hook
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 